# Generated by Django 2.2 on 2022-07-17 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
    ]
